language: scala
scala:
- 2.10.0
notifications:
  email:
  - viktor@farcic.com
deploy:
  provider: heroku
  api_key:
    secure: M+5P1xEMeWh7OSf1nV2PclTUBDb9pquwkSwyKSJM7gcCfUOgJTD3PQAAf4htmeSWoBGixFWy/HygsgLaZwZ5paqRT7mhl+AXUfxfyowqIzQuzfcvrEZjXiCLIJayjnJHPdW571vQjwknrs6AWvfzIy16J+02hBmr/9U7PLMy4R8=
  app: bddassistant
  on:
    repo: TechnologyConversations/TechnologyConversationsBdd
