language: scala
scala:
- 2.10.0
notifications:
  email:
  - viktor@farcic.com
deploy:
  provider: heroku
  api_key:
    secure: Dm6sUS/mQ93P1XGWxpzzstsnumUe4Ir7tfmD9nAFVWqj3FckfSUD4jKfTLwOziEiV5Dzxx0aHxBy52o8JkHaxBvFn3IjDArZE7IZobZ+ZL7LVahfyiL6sMXJvEtV3+UbwwwFi71xRG1voswsILu+7xzQyXsdfI3lXSIBbSuwHes=
  app: bddassistant
  on:
    repo: vfarcic/TechnologyConversationsBdd
