language: scala

scala:
- 2.11.2

notifications:
  email:
  - viktor@farcic.com

before_install: npm install -g grunt-cli

script:
  - sbt ++2.11.2 test
  - npm test
  - sbt "test:run-main models.jbehave.JBehaveRunnerAssistant --story_path public/stories/tcbdd/**/*.story -P browser=phantomjs -P url=http://localhost:1234 -P widthHeight=1024,768 --composites_path composites/TcBddComposites.groovy"
