# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos"
  config.vm.network :forwarded_port, host: 1234, guest: 80
  config.vm.provider "virtualbox" do |v|
    v.name = "bdd-assistant"
    v.memory = 1024
  end
end